name: IMU Broadcaster

on: [push]

jobs:
  build:
    runs-on: self-hosted
    container:
      image: mzandtheraspberrypi/imu_websocket_broadcaster:build-2023-08-26
      options: --cpus 1
    steps:
      # in a container git doesn't trust some stuff and submodules doesn't work
      # https://github.com/actions/checkout/issues/1169
      - name: git_correct_dir
        run: |
          git config --system --add safe.directory /__w/imu_websockets/imu_websockets
      - name: checkout_repo
        uses: actions/checkout@v2.3.4
        with:
          submodules: 'true'
      - name: examine_files
        run: |
          pwd
          ls -a
      - name: build
        run: |
          cd /__w/imu_websockets/imu_websockets/
          mkdir build
          cd build
          cmake -D BUILD_IMU_BROADCASTER_EXAMPLES=TRUE .. 
          make -j 1
